#!/usr/bin/env python3

import os
import json
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('data_dir')
parser.add_argument('output_file')

args = parser.parse_args()

_dir = args.data_dir
out_fname = args.output_file

years = sorted([int(y) for y in os.listdir(_dir)])

data = {}

for year in years:
    data[year] = {}
    months_dir = os.path.join(_dir, str(year))
    months = sorted([int(m) for m in os.listdir(months_dir)])
    for month in months:
        data[year][month] = {}
        days_dir = os.path.join(months_dir, str(month))
        days = sorted([int(d) for d in os.listdir(days_dir)])
        for day in days:
            leaf_dir = os.path.join(days_dir, str(day))
            day_data = {
                'answer': open(os.path.join(leaf_dir, 'answer')).read().strip()
                ,'notes': open(os.path.join(leaf_dir, 'notes')).read().strip()
            }
            data[year][month][day] = day_data

with open(out_fname, 'w+') as f:
    f.write(json.dumps(data))
